<a href="https://colab.research.google.com/github/Ubaldo-Yareli/M-todos-numericos/blob/main/Polinomio_de_Hermite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import sympy as sp

En el polinomio de Hermite, se utilizan ciertos valores de $x$ evaluados en un polinomio, es decir $f(x)$ y esos mismos valores de $x$ evaluados en la primera derivada de ese polinomio, es decir, $f'(x)$.

In [8]:
#Datos que se ocuparán
x=np.array([1.3, 1.6, 1.9]) #Valores de x
fx=np.array([0.6200860, 0.4554022, 0.2818186]) #Valores al evaluar "x" en el polinomio
derivada1x=np.array([-0.5220232, -0.5698959, -0.5811571]) #Valores de evaluar "x" en la primera derivada


In [13]:
import numpy as np
import sympy as sp
#Datos que se ocuparán
x=np.array([1.3, 1.6, 1.9])
fx=np.array([0.6200860, 0.4554022, 0.2818186])
derivada1x=np.array([-0.5220232, -0.5698959, -0.5811571])

# Paso 1: Crear la tabla z y Q
n=len(x)
z=np.zeros(2*n)
Q=np.zeros((2*n, 2*n))

# Paso 2: Asignar valores iniciales a z y Q
for i in range(n):
    z[2*i]=z[2*i+1]=x[i]
    Q[2*i][0]=Q[2*i+1][0]=fx[i]
    Q[2*i+1][1]=derivada1x[i]
    if i != 0:
        Q[2*i][1]=(Q[2*i][0]-Q[2*i-1][0])/(z[2*i]-z[2*i-1])

# Paso 3: Llenar la tabla Q con las diferencias divididas
for i in range(2, 2*n):
    for j in range(2, i+1):
        Q[i][j]=(Q[i][j-1]-Q[i-1][j-1])/(z[i]-z[i-j])


# Mostrar la tabla de diferencias divididas
print("Tabla de diferencias divididas:")
print(Q)

# Evaluar el polinomio en un punto
evaluacion = 1.5
valor=polinomio_Hermite(evaluacion)
print(f"El valor del polinomio evaluado en {evaluacion} es aproximadamente {valor}")


Tabla de diferencias divididas:
[[ 0.620086    0.          0.          0.          0.          0.        ]
 [ 0.620086   -0.5220232   0.          0.          0.          0.        ]
 [ 0.4554022  -0.548946   -0.08974267  0.          0.          0.        ]
 [ 0.4554022  -0.5698959  -0.069833    0.06636556  0.          0.        ]
 [ 0.2818186  -0.578612   -0.02905367  0.06796556  0.00266667  0.        ]
 [ 0.2818186  -0.5811571  -0.00848367  0.06856667  0.00100185 -0.00277469]]
El valor del polinomio evaluado en 1.5 es aproximadamente 0.5118277017283951


Al realizar la tabla, se repiten dos veces los valores de cada $f(x)$, en este caso, los valores de $0.6200860$, $0.4554022$ y $0.2818186$, y se denominan como $f[z_0]$, $f[z_1]$, etc. posteriomente, se encuentra las primeras diferencias divididas, las cuales, son ya sea la evaluacion en la primera derivada cuando los valores de $f(x)$ son los mismos o con la fórmula $f[z_1,z_2]=$$\frac{f[z_2]-f[z_1]}{z_2-z_1}$, cambiando los subíndices dependiendo de los valores de $f[z]$ que estén siendo utilizados.


El polinomio de Hermite se enscuentra con la fórmula $H_{2n+1}(x)=f[z_0]+\sum_{k=1}^{2n+1}f[z_0,..., z_k](x - z_0)(x - z_1)...(x - z_{k-1}).$
